#spring:
#  application:
#    name: bpmn-service
#  datasource:
#    url: jdbc:postgresql://192.168.111.52:5432/camunda
#    password: admin
#    username: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        jdbc:
#    show-sql: true
#  output:
#    ansi:
#      enabled: always
#  profiles:
#    active: dev
#

spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

camunda.bpm.admin-user:
  id: demo
  password: demo

server:
  port: 8081